# Generated by Django 6.0.6 on 2026-08-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_icon_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
