line-length = 210
target-version = "py312"  # adatta alla versione Python che usi

[lint]
select = ["E", "F", "I"]  # E=errori stile pep8, F=pyflakes (bug reali), I=import ordinati
ignore = []

exclude = [
    "migrations",
    ".venv",
]