# Generated by Django 6.0.6 on 2026-08-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='banner',
            field=models.ImageField(default='tournament_banners/default.png', upload_to='tournament_banners/'),
        ),
    ]
