# Generated by Django 6.0.6 on 2026-08-29 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_icon_alter_team_name'),
        ('tournaments', '0006_tournament_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('score_team1', models.PositiveIntegerField(blank=True, null=True)),
                ('score_team2', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('da_giocare', 'Da giocare'), ('conclusa', 'Conclusa')], default='da_giocare', max_length=20)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='teams.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='teams.team')),
            ],
            options={
                'ordering': ['round_number', 'id'],
            },
        ),
    ]
