# Generated by Django 6.0.6 on 2026-08-29 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='status',
        ),
    ]
